# -*- coding: utf-8 -*-
"""MCP 参数类型与描述（写入 JSON Schema 供 AI 阅读）。"""

from __future__ import annotations

from typing import Any, Literal, Optional, Union, get_args

from pydantic import Field
from typing_extensions import Annotated

# (python_type_name_for_exec, json_type, default_repr_for_exec, description)
PARAM_SPECS: dict[str, tuple[str, str, str, str]] = {
    "input_path": ("str", "string", '""', "本地输入文件绝对路径，例如 C:/Users/photo.jpg"),
    "output_path": ("str", "string", '""', "输出文件绝对路径；留空则自动生成到 MTools 输出目录"),
    "input_paths": ("str", "string", '""', "多个输入路径，逗号分隔（拼图合并）"),
    "text": ("str", "string", '""', "文本内容"),
    "left": ("int", "integer", "0", "裁剪/遮罩区域左边界（像素）"),
    "top": ("int", "integer", "0", "裁剪/遮罩区域上边界（像素）"),
    "right": ("int", "integer", "0", "裁剪/遮罩区域右边界（像素）"),
    "bottom": ("int", "integer", "0", "裁剪/遮罩区域下边界（像素）"),
    "width": ("int", "integer", "0", "目标宽度（像素），0 表示自动"),
    "height": ("int", "integer", "0", "目标高度（像素），0 表示自动"),
    "quality": ('Literal["high", "medium", "low"]', "string", '"medium"', "质量档位：high / medium / low"),
    "compress_mode_name": ('Literal["fast", "balanced", "max"]', "string", '"balanced"', "压缩模式"),
    "target_format": ("str", "string", '"png"', "目标格式扩展名，如 jpg / png / mp4 / mp3"),
    "keep_aspect": ("bool", "boolean", "True", "缩放时是否保持宽高比"),
    "rotate_mode": (
        'Literal["rotate_90", "rotate_180", "rotate_270", "flip_horizontal", "flip_vertical", "custom"]',
        "string",
        '"rotate_90"',
        "旋转模式",
    ),
    "angle": ("float", "number", "0.0", "自定义旋转角度（rotate_mode=custom 时）"),
    "color": ("str", "string", '"#FFFFFF"', "颜色，十六进制如 #FFFFFF"),
    "watermark_position": ("str", "string", '"bottom_right"', "水印位置：top_left / top_right / bottom_left / bottom_right / center"),
    "watermark_opacity": ("int", "integer", "128", "水印不透明度 0-255（视频会自动换算为 0-1）"),
    "font_size": ("int", "integer", "36", "水印字号"),
    "remove_mode": ('Literal["simple", "ai"]', "string", '"simple"', "去水印模式：simple 区域修复 / ai 模型修复"),
    "model_key": ("str", "string", '""', "ONNX 模型 key，留空用默认；需先在 MTools 下载模型"),
    "qrcode_level": ('Literal["L", "M", "Q", "H"]', "string", '"M"', "二维码纠错级别"),
    "color_space": ("str", "string", '"grayscale"', "目标色彩空间：grayscale/rgba/rgb/cmyk/lab/hsv/invert/sepia/binary"),
    "binary_threshold": ("int", "integer", "128", "二值化阈值"),
    "border_top": ("int", "integer", "10", "上边框宽度（像素）"),
    "border_bottom": ("int", "integer", "10", "下边框宽度（像素）"),
    "border_left": ("int", "integer", "10", "左边框宽度（像素）"),
    "border_right": ("int", "integer", "10", "右边框宽度（像素）"),
    "corner_radius": ("int", "integer", "0", "圆角半径（像素）"),
    "puzzle_rows": ("int", "integer", "3", "拼图行数"),
    "puzzle_cols": ("int", "integer", "3", "拼图列数"),
    "puzzle_spacing": ("int", "integer", "0", "拼图间距（像素）"),
    "puzzle_shuffle": ("bool", "boolean", "False", "是否打乱拼图块"),
    "puzzle_direction": ('Literal["horizontal", "vertical", "grid"]', "string", '"horizontal"', "拼图合并方向"),
    "grid_cols": ("int", "integer", "3", "网格列数（grid 模式）"),
    "gif_speed": ("float", "number", "1.0", "GIF 播放速度倍数"),
    "gif_reverse": ("bool", "boolean", "False", "是否反转 GIF 帧顺序"),
    "denoise_strength": ("int", "integer", "0", "增强后降噪强度 0-100，0 表示关闭"),
    "sharpen_strength": ("int", "integer", "0", "增强后锐化强度 0-100，0 表示关闭"),
    "speed": ("float", "number", "1.0", "倍速倍数，如 1.5 表示 1.5 倍速"),
    "bitrate": ("int", "integer", "128", "音频比特率 kbps"),
    "sample_rate": ("str", "string", '"original"', '采样率，如 44100；original 表示保持原样'),
    "channels": ("str", "string", '"original"', '声道数，如 2；original 表示保持原样'),
    "language": ("str", "string", '"zh"', "语言代码，如 zh / en"),
    "vocal_output": ('Literal["vocals", "instrumental", "both"]', "string", '"both"', "人声分离输出：vocals / instrumental / both"),
    "vcodec": ("str", "string", '"copy"', "视频编码器，copy 表示不重新编码"),
    "acodec": ("str", "string", '"copy"', "音频编码器，copy 表示不重新编码"),
    "watermark_text": ("str", "string", '""', "视频文字水印内容"),
    "multiplier": ("float", "number", "2.0", "插帧倍率，如 2.0 表示 2 倍帧率"),
    "subtitle_region": ("str", "string", '"bottom"', "字幕区域：bottom / top"),
    "vocal_keep": ('Literal["vocals", "instrumental"]', "string", '"vocals"', "视频人声分离保留轨"),
    "max_enhance_frames": ("int", "integer", "300", "视频增强最大处理帧数"),
    "target_encoding": ("str", "string", '"utf-8"', "目标文件编码"),
    "pattern": ("str", "string", '""', "正则表达式"),
    "timestamp": ("float", "number", "0.0", "Unix 时间戳"),
    "timestamp_unit": ('Literal["s", "ms"]', "string", '"s"', "时间戳单位：s 秒 / ms 毫秒"),
    "hash_algo": ('Literal["md5", "sha1", "sha256"]', "string", '"sha256"', "哈希算法"),
    "method": ("str", "string", '"GET"', "HTTP 方法：GET / POST / PUT / DELETE 等"),
    "url": ("str", "string", '""', "请求 URL 或 WebSocket 地址 ws:// / wss://"),
    "headers_json": ("str", "string", '"{}"', "请求头 JSON 对象字符串"),
    "body": ("str", "string", '""', "HTTP 请求体"),
    "body_type": ("str", "string", '"raw"', "请求体类型：raw / json / form"),
    "source_format": ("str", "string", '"json"', "源数据格式：json / yaml / xml / toml"),
    "target_lang": ("str", "string", '"zh-Hans"', "翻译目标语言"),
    "source_lang": ("str", "string", '""', "翻译源语言，留空自动检测"),
    "expires_in": ('Literal["1d", "7d", "30d"]', "string", '"7d"', "图床链接过期时间"),
    "storage_type": ('Literal["permanent", "temporary"]', "string", '"permanent"', "文件上传存储类型"),
    "temp_hours": ("str", "string", '"24h"', "临时文件保存时长"),
    "query_type": ('Literal["web", "app", "mapp", "kapp"]', "string", '"web"', "ICP 查询类型"),
    "domain": ("str", "string", '""', "域名或查询目标"),
    "windows_update_cmd": ('Literal["status", "disable", "restore"]', "string", '"status"', "Windows 更新：status / disable / restore"),
    "photo_width": ("int", "integer", "413", "证件照宽度（像素）"),
    "photo_height": ("int", "integer", "295", "证件照高度（像素）"),
    "bg_color": ("str", "string", '"#438EDB"', "证件照背景色"),
    "encode_type": ("str", "string", '"base64"', "编码类型：base64 / hex / url"),
    "decode_mode": ("bool", "boolean", "False", "true 表示解码，false 表示编码"),
    "left_text": ("str", "string", '""', "文本对比左侧内容"),
    "right_text": ("str", "string", '""', "文本对比右侧内容"),
    "crypto_algorithm": ("str", "string", '"SHA256"', "算法：MD5 / SHA256 / AES / DES 等"),
    "crypto_encrypt": ("bool", "boolean", "True", "true 加密/哈希，false 解密"),
    "crypto_mode": ("str", "string", '"CBC"', "对称加密模式：ECB / CBC"),
    "crypto_key": ("str", "string", '""', "加密密钥"),
    "crypto_iv": ("str", "string", '""', "加密 IV 向量"),
    "cron_expr": ("str", "string", '""', "Cron 表达式，如 0 9 * * 1-5"),
    "cron_count": ("int", "integer", "5", "返回未来 N 次执行时间"),
    "color_source": ("str", "string", '"hex"', "颜色源格式：hex / rgb"),
    "color_target": ("str", "string", '"rgb"', "颜色目标格式：hex / rgb"),
    "host": ("str", "string", '""', "主机名或 IP"),
    "ports": ("str", "string", '"80,443"', "端口列表，逗号分隔"),
    "dns_type": ("str", "string", '"A"', "DNS 记录类型：A / AAAA / MX / TXT 等"),
    "dns_server": ("str", "string", '"8.8.8.8"', "DNS 服务器"),
    "subtitle_text": ("str", "string", '""', "字幕文本内容（与 input_path 二选一）"),
    "encoding_action": ('Literal["detect", "convert"]', "string", '"detect"', "编码操作：detect 检测 / convert 转换"),
    "json_action": ('Literal["format", "minify"]', "string", '"format"', "JSON 操作：format 格式化 / minify 压缩"),
    "base_url": ("str", "string", '""', "OpenAI 兼容 API 地址，如 https://api.openai.com/v1"),
    "api_key": ("str", "string", '""', "API Key"),
    "model": ("str", "string", '""', "模型名称，如 gpt-4o-mini"),
    "crf": ("int", "integer", "0", "视频压缩 CRF，0 表示按 quality 档位自动；越小质量越高"),
    "scale": ("str", "string", '"original"', "分辨率：original / 4k / 2k / 1080p / 720p / 480p / 360p"),
    "fps": ("float", "number", "0.0", "目标帧率，0 表示保持原帧率"),
    "preset": ("str", "string", '"medium"', "编码预设：ultrafast…veryslow 或 medium"),
    "enhance_scale": ("int", "integer", "0", "视频增强放大倍数，0 表示用模型默认"),
    "bilingual": ("bool", "boolean", "False", "字幕是否双语（原文+译文）"),
    "burn_in": ("bool", "boolean", "False", "是否将字幕烧录进视频"),
    "segments_json": ("str", "string", '""', '字幕分段 JSON：[{"text":"...","start":0,"end":1.2}]'),
}


def atomic_tool_name(tool_id: str) -> str:
    return "mtools_" + tool_id.replace(".", "_")


def get_tool_id_literal() -> type:
    from mcp_server.tool_ids import TOOL_ID_MAP
    return Literal[tuple(TOOL_ID_MAP.keys())]  # type: ignore
