# -*- coding: utf-8 -*-
"""桌面版 tool_id 与 MCP action 映射（63 项，不含 dev.markdown_viewer）。"""

from __future__ import annotations

# tool_id -> (mcp_tool, action)
TOOL_ID_MAP: dict[str, tuple[str, str]] = {
    # 图片 20
    "image.compress": ("mtools_image", "compress"),
    "image.format": ("mtools_image", "format"),
    "image.resize": ("mtools_image", "resize"),
    "image.crop": ("mtools_image", "crop"),
    "image.rotate": ("mtools_image", "rotate"),
    "image.background": ("mtools_image", "background"),
    "image.watermark": ("mtools_image", "watermark"),
    "image.watermark_remove": ("mtools_image", "watermark_remove"),
    "image.info": ("mtools_image", "info"),
    "image.exif": ("mtools_image", "exif"),
    "image.qrcode": ("mtools_image", "qrcode"),
    "image.to_base64": ("mtools_image", "to_base64"),
    "image.gif": ("mtools_image", "gif"),
    "image.enhance": ("mtools_image", "enhance"),
    "image.puzzle.merge": ("mtools_image", "puzzle_merge"),
    "image.puzzle.split": ("mtools_image", "puzzle_split"),
    "image.search": ("mtools_image", "search"),
    "image.ocr": ("mtools_image", "ocr"),
    "image.color_space": ("mtools_image", "color_space"),
    "image.border": ("mtools_image", "border"),
    # 音频 6
    "audio.format": ("mtools_audio", "format"),
    "audio.compress": ("mtools_audio", "compress"),
    "audio.speed": ("mtools_audio", "speed"),
    "audio.vocal_extraction": ("mtools_audio", "vocal_extraction"),
    "audio.to_text": ("mtools_audio", "to_text"),
    "audio.text_to_speech": ("mtools_audio", "text_to_speech"),
    # 视频 12
    "video.compress": ("mtools_video", "compress"),
    "video.convert": ("mtools_video", "convert"),
    "video.extract_audio": ("mtools_video", "extract_audio"),
    "video.speed": ("mtools_video", "speed"),
    "video.vocal_separation": ("mtools_video", "vocal_separation"),
    "video.watermark": ("mtools_video", "watermark"),
    "video.repair": ("mtools_video", "repair"),
    "video.enhance": ("mtools_video", "enhance"),
    "video.interpolation": ("mtools_video", "interpolation"),
    "video.subtitle_remove": ("mtools_video", "subtitle_remove"),
    "video.subtitle": ("mtools_video", "subtitle"),
    "video.screen_record": ("mtools_video", "screen_record"),
    "video.ts_merge": ("mtools_video", "ts_merge"),
    # 开发 18
    "dev.base64_to_image": ("mtools_dev", "base64_to_image"),
    "dev.encoding": ("mtools_dev", "encoding_detect"),
    "dev.json_viewer": ("mtools_dev", "json_format"),
    "dev.http_client": ("mtools_dev", "http_request"),
    "dev.websocket_client": ("mtools_websocket", "connect"),
    "dev.encoder_decoder": ("mtools_dev", "encoder_decoder"),
    "dev.regex_tester": ("mtools_dev", "regex_test"),
    "dev.timestamp_tool": ("mtools_dev", "timestamp_convert"),
    "dev.jwt_tool": ("mtools_dev", "jwt_parse"),
    "dev.uuid_generator": ("mtools_dev", "uuid_generate"),
    "dev.color_tool": ("mtools_dev", "color_convert"),
    "dev.dns_lookup": ("mtools_dev", "dns_lookup"),
    "dev.port_scanner": ("mtools_dev", "port_scan"),
    "dev.format_convert": ("mtools_dev", "format_convert"),
    "dev.text_diff": ("mtools_dev", "text_diff"),
    "dev.crypto_tool": ("mtools_dev", "crypto"),
    "dev.sql_formatter": ("mtools_dev", "sql_format"),
    "dev.cron_tool": ("mtools_dev", "cron_parse"),
    # 其他 6
    "others.windows_update": ("mtools_others", "windows_update"),
    "others.image_to_url": ("mtools_others", "image_to_url"),
    "others.file_to_url": ("mtools_others", "file_to_url"),
    "others.icp_query": ("mtools_others", "icp_query"),
    "others.id_photo": ("mtools_others", "id_photo"),
    "others.translate": ("mtools_others", "translate"),
}
